### ISSUE TITLE
Add Support for Parameter Defaults

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#13]
This is probably a non-trivial issue, but it would be great if parameters could be initialized with default values based on the `Default Value` setting in the UserData Editor.

**Comment by NiklasRosenstein** [comment]
This should already work -- at least for LONG, REAL, VECTOR and COLOR parameters.

**Comment by NiklasRosenstein** [comment]
Afaik, you can not set the default value for eg. for String or Gradient parameters in the description resource. That would need to be added to the generated Python plugin file.

**Comment by donovankeith** [comment]
This is the .res file that's generated:

```
CONTAINER Ocvcube {
	INCLUDE Obase;
	NAME Ocvcube;
	GROUP ID_OBJECTPROPERTIES {
		VECTOR CV_CUBE_SIZE { DEFAULT 100.0 100.0 100.0; MIN 0.0 0.0 0.0; MAX 1.79769313486e+308 1.79769313486e+308 1.79769313486e+308; }
		VECTOR CV_CUBE_SEGMENTS { DEFAULT 2.0 2.0 2.0; MIN 1.0 1.0 1.0; MAX 1000.0 1000.0 1000.0; }
	}
}
```

But this is what I see in C4D:

![image](https://user-images.githubusercontent.com/4267389/36336382-1db1235c-133c-11e8-9833-cf35d1a6fed3.png)

Expected based on the UserData:
![image](https://user-images.githubusercontent.com/4267389/36336396-3bdf9de0-133c-11e8-837f-eb8fd0eec1c6.png)

C4D doesn't seem to be using the defaults - perhaps it's something that has to be done in Python code?

Also, `Limit Max` isn't active, yet a value is being added to the Resource file:
![image](https://user-images.githubusercontent.com/4267389/36336404-514fd12c-133c-11e8-853c-c75386469d8a.png)
`VECTOR CV_CUBE_SIZE { DEFAULT 100.0 100.0 100.0; MIN 0.0 0.0 0.0; MAX 1.79769313486e+308 1.79769313486e+308 1.79769313486e+308; }`

**Comment by NiklasRosenstein** [comment]
Oh right, I forgot. The default you set in the description is what you get when you do Right Click > Reset to Default on the parameter. The actual value still needs to be set in `Init()`.

**Comment by NiklasRosenstein** [comment]
> Also, Limit Max isn't active, yet a value is being added to the Resource file:

Hm, there seems to be no (documented) symbols that describe the "Limit Min" or "Limit Max" checkboxes in the UserData. I'll have to find out how to read that checkbox value first.

**Comment by NiklasRosenstein** [comment]
I've moved the issue of the Limit Min/Limit Max settings to a different issue.

**Comment by NiklasRosenstein** [comment]
Fixed in https://github.com/NiklasRosenstein/c4d-prototype-converter/commit/9eb96d8ce66b9128fca2ede1a242851f4e786280
