### ISSUE TITLE
BUG: No Attribute `DTYPE_GRADIENT`

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#2]
When attempting to convert [CV-Parametric Selection Tag](https://www.cineversity.com/vidplaylist/cv-parametric_selection_tag) I got this error in the console:
![image](https://user-images.githubusercontent.com/4267389/36280922-bb0e6390-1250-11e8-9e13-fe142f24f429.png)

Converting this tag was the motivation behind this project, so it will certainly be a challenge, but if it's possible to get it working, that would be amazing.

**Comment by NiklasRosenstein** [comment]
Fixed in 3195e0c2afedab7796d2f39e47e61d7857a51db0
