### ISSUE TITLE
Add an About/Help Pulldown

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#24]
It would be nice if there was an easy way to access the documentation for the plugins from within the plugins.

* Help
    * [Show Help](https://github.com/NiklasRosenstein/c4d-prototype-converter)
    * [Report Bug/Idea](https://github.com/NiklasRosenstein/c4d-prototype-converter/issues)
    * About

**Comment by donovankeith** [comment]
Also, right-clicking on a parameter and choosing "Show Help" should link to an overview of the parameters in this repo.

**Comment by NiklasRosenstein** [comment]
> Also, right-clicking on a parameter and choosing "Show Help" should link to an overview of the parameters in this repo.

No idea if that's possible.

**Comment by NiklasRosenstein** [comment]
> Also, right-clicking on a parameter and choosing "Show Help" should link to an overview of the parameters in this repo.

I've left this one out. For one, we don't have a description for every parameter yet, and as already noted, I don't even know if that right-click thing is possible in a dialog.

**Comment by donovankeith** [comment]
Not sure if this will work for a dialog or not, but R19 added:
https://developers.maxon.net/docs/Cinema4DPythonSDK/html/modules/c4d.plugins/index.html?highlight=help%20callback#c4d.plugins.RegisterPluginHelpCallback

Also, no need to have info on each parameter. I'd say it's enough to just show the Readme/Wiki on GitHub.

**Comment by NiklasRosenstein** [comment]
This is for description parameters in node plugins.

**Comment by donovankeith** [comment]
Works great!

![image](https://user-images.githubusercontent.com/4267389/36809121-dfafd924-1c7b-11e8-8038-bcbb0d718505.png)

![image](https://user-images.githubusercontent.com/4267389/36809112-d9166d94-1c7b-11e8-80d0-12dc7b53b85b.png)
