### ISSUE TITLE
AutoFill PluginName and Help with Docstring

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#28]
![image](https://user-images.githubusercontent.com/4267389/36570102-5a095efc-17e5-11e8-80b6-e08bd322555d.png)

`Name-US:` -> `Plugin Name`
`Description-US:` -> `Plugin Help` / status bar text.

It seems like this might already be implemented. If so, just ensure that the `Plugin Name` field updates to show the name from `Name-US` rather than the filename.

**Comment by NiklasRosenstein** [comment]
This is already implemented. Weird that your screenshot doesn't show it. Please get the newest version and try again. If it is still not displayed correctly, I'll have to take another look at it.

**Comment by donovankeith** [comment]
Just tried again using the latest version. I think that the generated plugin uses the correct info, but the GUI doesn't reflect the appropriate `Plugin Name`.

![image](https://user-images.githubusercontent.com/4267389/36570366-8b4cdfd8-17e6-11e8-84d2-2a70bda8fd0a.png)
