### ISSUE TITLE
Add a TODO List of Common Issues to Check to the Plugin Stub

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#29]
There will inevitably be limits to this auto-conversion process. As much as possible, let's document the most common ones and include them as `# TODO:` items in the plugin template. Ideally close to the location where the change would need to occur.

I'm not sure what these are/should be, but I just wanted to start this issue to record and brainstorm.

```python
"""
# TODO: Delete the old/redundant `__main__` check.
# TODO: Customize the icon for this plugin.
# TODO: Delete the original script so there aren't name conflicts when users search with The Commander (`shift + c`)
# TODO: Remove redundant imports
# TODO: Update Copyright information
# TODO: Add a README file
"""
```

**Comment by NiklasRosenstein** [comment]
> TODO: Customize the icon for this plugin

I feel like this is a bit too obvious.

> TODO: Delete the original script so there aren't name conflicts when users search with The Commander (`shift + c`)

And users won't have this issue because they haven't gotten a version of your prototype usually, or if they do, it's something that you have to tell them.
