### ISSUE TITLE
BUG: Not possible to edit auto-set parameters

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#3]
To reproduce:

![image](https://user-images.githubusercontent.com/4267389/36281058-2fe74682-1251-11e8-8d83-c3fbf06c78dd.png)

1. Drag a BaseList2D w/ UserData into the Source field.
![image](https://user-images.githubusercontent.com/4267389/36281096-49fefcae-1251-11e8-9ba6-71740265d98b.png)

> Notice that the `Plugin Name` ends in v1.0.0 (from the name of the tag)

2. Try to select or edit the text in `Plugin Name`

![image](https://user-images.githubusercontent.com/4267389/36281145-75c38a44-1251-11e8-9f40-c235acd04ca7.png)

BUG: You can't

Expected: Dragging something into the Link field will auto-fill the contents, however, you should be able to manually edit those auto-generated values after the fact.

**Comment by NiklasRosenstein** [comment]
The auto-filled content you see is *helptext* -- i.e. it is only a suggestion. In the current version, this is visually indicated by the text color.

I suppose we could change that by inserting actual text into the fields automatically when an object is dragged into the link field -- however you would loose the automatic adapation in the other fields when you modify the Plugin Name field.

On a side note, when the object was used to generated description resources once and is dragged into the dialog again, *all* fields will be filled with the values that were last used during the export.

**Comment by donovankeith** [comment]
Now that the text is grayed out initially, it's much more clear what's going on.
![image](https://user-images.githubusercontent.com/4267389/36332482-30f8ca74-1327-11e8-8a40-772e8612f343.png)

I think this can safely be closed.
