### ISSUE TITLE
"default-icon.tiff" Does Not Exist

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#37]
![image](https://user-images.githubusercontent.com/4267389/36807439-d856d6e0-1c77-11e8-8b83-0f2e9018bcb6.png)

Seems like the `res` folder got dropped from the repo at some point.

**Comment by donovankeith** [comment]
Manually placing a fie in that location doesn't seem to fix the error.

**Comment by NiklasRosenstein** [comment]
The file was moved inside the plugin directory. Try the "Clear Settings" from the File menu

**Comment by NiklasRosenstein** [comment]
I think this can be closed with the resolution of #42.
