### ISSUE TITLE
IDEA: Auto-generate 32x32px Icon if None is Specified

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#4]
Low Priority:
If no Icon is specified by the user, auto-generate a 32x32px .tif icon inside of the `res/` folder. Perhaps you could just auto-link the Icon field to a default icon file?

**Comment by NiklasRosenstein** [comment]
This issue was accidentally closed by referencing the wrong issue in the commit message.

**Comment by NiklasRosenstein** [comment]
The converters now fall back to the default icon in the `res/icons` directory.
