### ISSUE TITLE
`Cancel` Button doesn't close free-floating `Prototype Converter`

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#40]
1. Open the Prototype Converter
![image](https://user-images.githubusercontent.com/4267389/36809032-a30adb40-1c7b-11e8-8397-61c23ad765bf.png)

2. Press Cancel
![image](https://user-images.githubusercontent.com/4267389/36809044-a9d3617c-1c7b-11e8-80a8-5005762efae0.png)

> Nothing happens.

Not sure what the intent of the Cancel button is. Perhaps it should close the dialog, or just not exist as it's an ASync dialog?

**Comment by NiklasRosenstein** [comment]
It's a bug that it does nothing.

> Not sure what the intent of the Cancel button is. Perhaps it should close the dialog, or just not exist as it's an ASync dialog?

It was in your original Mockup, so I kept it. We could just remove it

**Comment by donovankeith** [comment]
Better without. Also, I like that `Create` was moved to the far right.
![image](https://user-images.githubusercontent.com/4267389/36863710-5cd0a82a-1d3f-11e8-8fe0-1e49dbe5a2dc.png)
