### ISSUE TITLE
Script Converter: `main` is not defined

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#41]
Try to convert the script in this .zip file.

```python
"""Name-US: CV-Hello World
Description-US: Simple plugin that opens a dialog.
"""

import c4d
from c4d import gui


def main():
    gui.MessageDialog('Hello World!')

if __name__=='__main__':
    main()
```

[cv-hello-world.zip](https://github.com/NiklasRosenstein/c4d-prototype-converter/files/1768579/cv-hello-world.zip)

You'll get this error:

```
Traceback (most recent call last):
  File "'cv-hello-world.pyp'", line 27, in <module>
NameError: name 'main' is not defined
```

It seems like the issue is this redundant `main()`:

```python
if __name__=='__main__':
    main()
```

**Comment by NiklasRosenstein** [comment]
We've talked about this before in #27. I suppose figuring out this exact portion is possible, but anything more complex under the check should be removed manually.

**Comment by donovankeith** [comment]
Thanks for making this change. I can now convert most of my simple scripts without any manual intervention.
