### ISSUE TITLE
File > Clear Settings Doesn't Always Clear Settings

### ISSUE THREAD

**Issue by donovankeith** [NiklasRosenstein/c4d-prototype-converter#42]
![image](https://user-images.githubusercontent.com/4267389/36809990-6d704f30-1c7e-11e8-8426-06e7731ab6c0.png)

File > Clear Settings didn't restore this to default settings.

[CV-Parametric.zip](https://github.com/NiklasRosenstein/c4d-prototype-converter/files/1768617/CV-Parametric.zip)

**Comment by NiklasRosenstein** [comment]
Clear settings only removes the information stored in the object, not the values currently in the dialog. Maybe change its behaviour or change the name

**Comment by donovankeith** [comment]
I think this should flush the stored settings and revert to default (what you would get when you first drag an object into the Source field). No need to change the name.

**Comment by donovankeith** [comment]
Also, the same option should probably be available in the Script Converter as well.

**Comment by NiklasRosenstein** [comment]
![image](https://user-images.githubusercontent.com/1318438/36935058-85ed39d0-1ef2-11e8-9b4e-37eeb02aaadb.png)

Add clear buttons for every field instead
