### ISSUE TITLE
"Animatable" user data parameter - error when OFF

### ISSUE THREAD

**Issue by ariellevesque** [NiklasRosenstein/c4d-prototype-converter#49]
When the "Animatable" checkbox is unchecked in the user data manager properties menu, the TagData Plugin fails to load - the error message points to the .res file line wherever there's an ANIMATE OFF;

Leaving all parameters animatable fixes it, or removing all instances of "ANIMATE OFF;" in the res file... But I'd like to have several fields that can't be animated...

**Comment by NiklasRosenstein** [comment]
Hello @ariellevesque, thanks for reporting this issue. This is due to a mistake in the plugin:

https://github.com/NiklasRosenstein/c4d-prototype-converter/blob/09bffb86db343369c002a03a40345d2ee7237dad/c4d_prototype_converter/ui/PrototypeConverter.py#L493-L496

It should read `ANIM OFF;` and `ANIM MIX;`.

**Comment by NiklasRosenstein** [comment]
@ariellevesque  Please verify if the problem has been fixed!

[c4d_prototype_converter-v1.1.0-3-gd436889.tar.gz](https://github.com/NiklasRosenstein/c4d-prototype-converter/files/2173041/c4d_prototype_converter-v1.1.0-3-gd436889.tar.gz)

**Comment by NiklasRosenstein** [comment]
@ariellevesque Please try this one instead: 
[c4d_prototype_converter-v1.1.0-4-gae00105.tar.gz](https://github.com/NiklasRosenstein/c4d-prototype-converter/files/2173050/c4d_prototype_converter-v1.1.0-4-gae00105.tar.gz)

**Comment by ariellevesque** [comment]
@NiklasRosenstein amazing!
Yep, it works without issues - thanks for the quick fix!

**Comment by NiklasRosenstein** [comment]
Thanks for the feedback. You can grab the v1.2.0 release now:

https://github.com/NiklasRosenstein/c4d-prototype-converter/releases/tag/v1.2.0
